### ISSUE TITLE
Please release

### ISSUE THREAD

**Issue by nim-nim** [gofed/symbols-extractor#144]
Please don’t replicate the problems of the other Go projects we’re trying to package in Fedora

**Comment by ingvagabund** [comment]
Then let's create a list of things we want in the first release I guess? @nim-nim can you make such list?

**Comment by nim-nim** [comment]
Honestly, the only things that would be worth fixing before a release would be:
* adding licensing
* updating to a non obsolete release of urfave (so it does not need importing as a compat package in devel)

Everything else can be fixed/enhanced afterwards, a formal release is not the end of the project, it's just the beginning.

You can release as 0.1 if that makes you feel better.

**Comment by nim-nim** [comment]
Fixed in https://pagure.io/golist
