### ISSUE TITLE
incorect evaluation of literals for binary expression

### ISSUE THREAD

**Issue by pirat89** [gofed/symbols-extractor#19]
Literals inside the binary expression `8 * 3.1` are incorrectly evaluated as different types, where
- `8` is evaluated as `int`
- `3.1` is evaluated as `float`

But in this case golang automatically retype `8` to `float` (or more precisely `float64`). For expressions where operands are given as basic literals, an extra type checking should be done.

Output from test:
```bash
--- FAIL: TestParseBinaryExpr1 (0.00s)
	gen_expression_test.go:97: Unexpected error for expr '8 * 3.1': Binary operation "*" over two different types: "int" != "float"
```

**Comment by ingvagabund** [comment]
If the literals are given via variables, the go complains about types mismatch [1].
So the implicit conversion is done over number literals only [2]

[1] https://play.golang.org/p/6Cj85TJdGg
[2] https://play.golang.org/p/fgA4OPcDEz

**Comment by ingvagabund** [comment]
Fixed
