### ISSUE TITLE
parseBinaryExpr: return variable instead of type?

### ISSUE THREAD

**Issue by pirat89** [gofed/symbols-extractor#20]
Assume that we have this inside SymTab:
```
type MyInt int
var Foo MyInt
```
Then function `parseBinaryExpr` evaluates the **`Foo + 2`** expression as identifier **`Foo`**. Is it correct   result or `MyInt` should be returned instead?

**Comment by ingvagabund** [comment]
`MyInt` it is. Fixed by https://github.com/gofed/symbols-extractor/commit/d32feffdcf889672f48108e6f05fc2bb7261338e
