### ISSUE TITLE
parseBinaryExpr: troubles with parethesised expressions

### ISSUE THREAD

**Issue by pirat89** [gofed/symbols-extractor#28]
Parsing of expressions with parethessis fails:
```
--- FAIL: TestParseBinaryExpr25 (0.00s)
	gen_expression_test.go:321: Unexpected error for expr 'true || ((5+1) * (MyFunc(11) / MyInt(14))) > 0': Unrecognized expression: &ast.ParenExpr{Lparen:9, X:(*ast.BinaryExpr)(0xc4201fda70), Rparen:42}
```

**Comment by pirat89** [comment]
The commit resolves just currently tested problems inside `parseBinaryExpr`. However as I see, the parenthesis will provide troubles on various places of the code. One possible solution can be includeed call of `parseParenExpr` on various places inside *expression.go* (like in the patch above). But it doesn't seem like good solution - and definitely, this will not resolve troubles in case that parenthesis are used for whole right side in assgnment, for example `var Foo int = (5 + 1)`.

In case that there is not specific reason to exclude `parseParenExpr` from Parse function, possible generic solution would be:
```patch
diff --git a/pkg/parser/expression/expression_parser.go b/pkg/parser/expression/expression_parser.go
index 1219439..d547ca5 100644
--- a/pkg/parser/expression/expression_parser.go
+++ b/pkg/parser/expression/expression_parser.go
@@ -825,6 +825,9 @@ func (ep *Parser) Parse(expr ast.Expr) ([]gotypes.DataType, error) {
        case *ast.BinaryExpr:
                def, err := ep.parseBinaryExpr(exprType)
                return []gotypes.DataType{def}, err
+       case *ast.ParenExpr:
+               def, err := ep.Parse(ep.parseParenExpr(exprType))
+               return def, err
        case *ast.CallExpr:
                // If the call expression is the most most expression,
                // it may have a different number of results
```

Tests in master branch still pass, so in case this is correct solution, I will modify the commit above. What do you think @ingvagabund ?

**Comment by ingvagabund** [comment]
Fixed
