### ISSUE TITLE
functionParser.go: parseBinaryExpr returns only gotypes.Builtin{}

### ISSUE THREAD

**Issue by pirat89** [gofed/symbols-extractor#5]
The parseBinaryExpr returns only &gotypes.Builtin{} type as result data type. However binare operator can be used on simple data types based on builtin types and as result produce user's defined data type. Try:
```golang
package main

import "fmt"
type Pp int
func main() {
        var foo Pp = 5
        var foo2 Pp = 3
        res := foo * foo2
	fmt.Printf("%v :: %T\n", res, res)
        # result: main.Pp :: 15
}
```

So parseParseBinaryExpr should return relevant type instead of builtin (or something else, but not builtin)

**Comment by ingvagabund** [comment]
implemented at https://github.com/gofed/symbols-extractor/blob/bc618b4a052f5d33bcb82a78e2ef9ef218e247ce/pkg/parser/expression/parser.go#L382-L401
